name: Check

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:
  workflow_call:

jobs:
  code-quality:
    name: Code Quality

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Biome
        uses: biomejs/setup-biome@v2.6.0

      - name: Run Biome
        run: biome ci
